[[headers]]
  for = "/*"
  [headers.values]
    # Allow other sites to iframe
    X-Frame-Options = ""
    # Lets widget fetch its own data and load images
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://api.yourdomain.com; img-src 'self' data: https:; frame-ancestors *;"
